name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull rexhonz77/products-microservice:latest
      - name: Delete old container
        run: docker rm -f products-microservice-container || true
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name products-microservice-container rexhonz77/products-microservice:latest
      - name: Build Docker image
        run: |
          docker build -t products-microservice .
          docker tag products-microservice rexhonz77/products-microservice:latest
          docker push rexhonz77/products-microservice:latest
